import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "./nav-bar";

const gilroy = localFont({
  src: [
    { path: "../../public/assets/fonts/Gilroy-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Bold.woff2", weight: "700", style: "normal" },
  ],
});

export const metadata = {
  title: "Scissor - Brief is the new black. Make your URL shorter",
  description:
    "Brief is the new black. Scissor is a simple tool which makes URLs as short as possible. Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${gilroy.className} text-text-400`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

export function Container({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return <div className={`container | ${className} px-[5%] mx-auto `}>{children}</div>;
}
