"use client";
import { Footer } from "@/components/common";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "./nav-bar";

const gilroy = localFont({
  src: [
    { path: "../../public/assets/fonts/Gilroy-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Semibold.woff2", weight: "600", style: "normal" },
    { path: "../../public/assets/fonts/Gilroy-Bold.woff2", weight: "700", style: "normal" },
  ],
});

export const metadata = {
  title: "Scissor - Brief is the new black. Make your URL shorter",
  description:
    "Brief is the new black. Scissor is a simple tool which makes URLs as short as possible. Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${gilroy.className} text-text-400`}>
        <div className="page-wrapper | grid grid-rows-[auto_1fr_auto] min-h-screen">{children}</div>
      </body>
    </html>
  );
}

export function LandingPageLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <NavBar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
